{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Percolational regions as a polycentricity measure"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "import os\n",
    "import pandas as pd\n",
    "import geopandas as gpd\n",
    "import numpy as npa\n",
    "from sklearn.cluster import DBSCAN"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "os.chdir('D:/bachelors/datasets/')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Preparation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('Variables/mappers/communes_names_map.json') as infile:\n",
    "    names_map = json.load(infile)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "nodes_path = 'analysis/yearly_graphs_v4/total/nodes_total_{}.csv'\n",
    "datatables_path = 'translated_data_v4/data_{}.csv'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def read_raw_data(datatable_path):\n",
    "    df_current = pd.read_csv(datatable_path)\n",
    "#     df_current['geo_departure'], df_current['geo_arrival'] = df_current['geo_departure'].map(names_map), df_current['geo_arrival'].map(names_map)\n",
    "    df_current.dropna(subset = ['geo_departure', 'geo_arrival'], inplace = True)\n",
    "#     df_current = df_current[df_current.geo_departure != df_current.geo_arrival]\n",
    "    df_current = pd.pivot_table(df_current, 'uid_person', 'geo_departure', 'geo_arrival', aggfunc = 'nunique')\n",
    "    df_current.values[[np.arange(df_current.shape[0])]*2] = 0\n",
    "    maxim = np.max(df_current.fillna(0).values)\n",
    "    df_current = ((df_current / maxim) * -1 + 1).fillna(1)\n",
    "    \n",
    "    return df_current"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Create a list of epsilon values to cluster"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "epses = [float(i[:4]) for i in np.arange(0.1, 1.01, 0.01).astype(str).tolist()] "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "epses = [i/100 for i in range(1, 101)]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Plot tools"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "from matplotlib import font_manager as fm\n",
    "import matplotlib\n",
    "\n",
    "medium_font = fm.FontProperties(fname =  \"D:/bachelors/datasets/viz/Roboto-Medium.ttf\", size = 12)\n",
    "regluar_font = fm.FontProperties(fname = \"D:/bachelors/datasets/viz/Roboto-Regular.ttf\", size = 12)\n",
    "\n",
    "colors = {\n",
    "    'peach' : '#FCB886',\n",
    "    'blue' : '#6FC7F7',\n",
    "    'green' : '#78AF34',\n",
    "    'red' : '#D25B5B',\n",
    "    'grey' : '#8B8B8B'\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "def model_regions(dat):\n",
    "    \"\"\"Builds hierarchy of regions for a distance matrix\"\"\"\n",
    "    series_list = []\n",
    "    for eps in epses:\n",
    "        labs = DBSCAN(eps = eps, min_samples = 2, metric = 'precomputed').fit(dat).labels_\n",
    "        series_list.append(pd.Series(labs, dat.index).rename(f'percolation_{eps}'))\n",
    "    percolation_classes = pd.DataFrame(series_list).transpose()\n",
    "    percolation_classes = percolation_classes.applymap(lambda elem: None if elem == -1 else elem)\n",
    "    return percolation_classes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "def map_series(series):\n",
    "    if series.name in dict_perc_reg.keys():\n",
    "        return series.map(dict_perc_reg[series.name])\n",
    "    else:\n",
    "        return series"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('Variables/mappers/communes_names_toRussian_map.json') as infile:\n",
    "    rus_names = json.load(infile)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_percolation(matrix, year):\n",
    "    plt.figure(figsize = (11,11))\n",
    "\n",
    "    ax = sns.heatmap(matrix,\n",
    "                     linewidths = .3,\n",
    "                     zorder = 1,\n",
    "                     cmap = 'viridis',\n",
    "                     cbar = False)\n",
    "    plt.grid(ls = ':', zorder = 0)\n",
    "    plt.xticks(fontproperties = regluar_font)\n",
    "\n",
    "    plt.yticks(fontproperties = regluar_font)\n",
    "    ax.set_title(f'{year}', loc = 'left', fontproperties = medium_font, fontsize=24)\n",
    "    ax.set_xlabel('Фильтр интенсивности поездок', fontproperties = medium_font, fontsize=18)\n",
    "    ax.set_ylabel('Главный муниципалитет кластера', fontproperties = medium_font, fontsize=18)\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(f'analysis/percolation_regions/plots_v4/{year}_percolation.png')\n",
    "    plt.close('all')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "\n",
    "def round_down(n, decimals=0):\n",
    "    multiplier = 10 ** decimals\n",
    "    return math.floor(n * multiplier) / multiplier"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "bounds = gpd.read_file('../qgis/base/Netherlands_communes.gpkg')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "from collections import defaultdict"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "def percolation_regions_resample(percolation_classes, year):\n",
    "    df = percolation_classes.drop(columns = ['flow_cent']).stack().reset_index().rename(columns = {\n",
    "        'commune' : 'NAME',\n",
    "        'level_1' : 'percolation_threshold',\n",
    "        0 : 'parent'\n",
    "    }).assign(\n",
    "        year = year\n",
    "    )\n",
    "    \n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    }
   ],
   "source": [
    "sustain = []\n",
    "regions_cores_list = []\n",
    "region_to_core_map = defaultdict(dict)\n",
    "percolation_regions = []\n",
    "for year in range(2004,2018):\n",
    "    dat = read_raw_data(datatables_path.format(year))\n",
    "    nodes = pd.read_csv(nodes_path.format(year))\n",
    "    \n",
    "    percolation_classes = model_regions(dat)\n",
    "    percolation_classes = percolation_classes.reset_index().merge(nodes[['commune', 'flow_cent']], left_on = 'geo_departure', right_on = 'commune', how = 'left').drop(columns = ['geo_departure'])\n",
    "    dict_perc_reg = {\n",
    "        f'percolation_{eps}' : percolation_classes.set_index(\n",
    "            'commune'\n",
    "        ).groupby(\n",
    "            f'percolation_{eps}'\n",
    "        )['flow_cent'].idxmax().to_dict() for eps in epses\n",
    "    }\n",
    "    percolation_classes = percolation_classes.apply(map_series).apply(\n",
    "        lambda x: x.map(rus_names) if x.name not in ['commune', 'flow_cent'] else x\n",
    "    )\n",
    "\n",
    "    matrix = percolation_classes.drop(columns = ['flow_cent', 'commune']).apply(lambda column: column.value_counts())\n",
    "    percolation_classes = percolation_classes.set_index('commune')\n",
    "    percolation_regions.append(percolation_regions_resample(percolation_classes, year))\n",
    "    matrix.columns = [float(i.split('_')[1]) for i in matrix.columns]\n",
    "    matrix = matrix.sort_values(by = list(matrix.columns))\n",
    "    first_value = matrix.dropna(axis=1, how = 'all').columns[0]\n",
    "    matrix = matrix.loc[:, round_down(first_value, 1):]\n",
    "#     break\n",
    "    matrix = matrix.assign(\n",
    "        order = matrix.apply(lambda row: row.loc[row == row.dropna().iloc[0]].index[0], axis = 'columns'),\n",
    "        parent = matrix.apply(\n",
    "            lambda row: round(row.loc[row == row.dropna().iloc[-1]].index[0] + .01, 2) if \\\n",
    "            row.loc[row == row.dropna().iloc[-1]].index[0] < 1 else 1,\n",
    "            axis = 'columns'),\n",
    "        duration = matrix.apply(lambda x: x.isnull().sum(), axis='columns')\n",
    "    )\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "#     matrix['order'] = matrix.apply(lambda row: row.loc[row == row.dropna().iloc[0]].index[0], axis = 'columns')\n",
    "#     matrix['duration'] = matrix.apply(lambda x: x.isnull().sum(), axis='columns')\n",
    "#     matrix['parent'] = matrix.apply(lambda row: row.loc[row == row.dropna().iloc[-1]].index[0] + .01, axis = 'columns')\n",
    "    matrix = matrix.sort_values(by = ['order', 'duration'])\n",
    "    plot_percolation(matrix.drop(columns = ['order', 'duration', 'parent']), year)\n",
    "    \n",
    "    cutpoint_core = matrix['order'].to_dict()\n",
    "    parent_core = matrix['parent'].to_dict()\n",
    "    matrix.drop(columns = ['order', 'parent', 'duration'], inplace = True)\n",
    "#     break\n",
    "    sustain.append(len(matrix.columns) - matrix.isna().sum(axis = 'columns').mean())\n",
    "    regions_cores = {}\n",
    "    for name, cpt in cutpoint_core.items():\n",
    "        regions_cores.update(\n",
    "            percolation_classes[percolation_classes[f'percolation_{cpt}'] == name][f'percolation_{cpt}'].to_dict()\n",
    "        )\n",
    "        \n",
    "    parent_cores = {}\n",
    "    for name, cpt in parent_core.items():\n",
    "        parent_cores.update(\n",
    "            percolation_classes[percolation_classes[f'percolation_{cpt}'] == name][f'percolation_{cpt}'].to_dict()\n",
    "        )\n",
    "\n",
    "    \n",
    "    sustainability = percolation_classes.drop(columns = ['flow_cent']).apply(\n",
    "        lambda x: x.value_counts(), axis = 'rows'\n",
    "    ).dropna(how = 'all').dropna(axis = 'columns', how = 'all')\n",
    "    sustainability['sust'] = sustainability.apply(lambda x: sustainability.shape[1] - x.isnull().sum(), axis='columns')\n",
    "    \n",
    "    bounds['parent'] = bounds['NAME'].map(regions_cores)\n",
    "    bounds['sustain'] = bounds['parent'].map(sustainability['sust'].to_dict())\n",
    "    bounds.to_file(f'analysis/percolation_regions/{year} region cores sustain_v2.gpkg', driver = 'GPKG')\n",
    "    \n",
    "    region_to_core_map[str(year)] = regions_cores    \n",
    "    regions_cores_list.append(bounds.assign(core = lambda frame: frame.NAME.map(regions_cores), \n",
    "                                            year = year))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAA+gAAAHwCAYAAAA1uUU7AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjMsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+AADFEAAAgAElEQVR4nO3dd5RU9d0/8M/IAiKdSFkSml2RhCjHgkZUEFEsESuoSKKCwRKSEFNMsDfcWLHtYwTEQh6MMehPUaKoMZEIYouxJQJSFlGioCgsu9zfHx72hMeSAWb2XpzX65w9Mndm537eZ4d13nzvvZNLkiQJAAAAIFVbpD0AAAAAoKADAABAJijoAAAAkAEKOgAAAGSAgg4AAAAZoKADAABABijoAAAAkAH1VtA/+uijuO2222KvvfaK5557LiIiamtrY/To0VFeXh6dOnWKK664or7GAQAAgEwpq4+dfPTRR9G1a9fo27dvvPHGG5EkSURE3HvvvfH444/HK6+8EitWrIh99tkn9t9//9hrr73qYywAAADIjHop6E2aNIk333wzWrduHV27dq3bPm3atBg2bFi0adMm2rRpE8ccc0w8/PDDCjoAAAAlp14KeoMGDaJ169af2V5VVRUDBgyou11eXh5z58793OeorKyMysrKiIj4xz/+EZ06dSrOsAAAAFBEy5Yti/fee+8z2+uloH+RVatWRYMGDepul5WVxerVqz/3scOHD4/hw4dHRESvXr1i9uzZ9TIjAAAAFFKvXr0+d3uqV3Fv3Lhx1NTU1N2ura2Nhg0bpjgRAAAApCPVgl5eXh4LFiyou11VVRUdOnRIcSIAAABIR6oF/ZBDDonx48fH0qVL4+2334577703Dj744DRHAgAAgFSkeg76McccE7NmzYpvfvOb0bBhwxg1alTsu+++aY4EAAAAqcgl6z6UfDPiInEAAABsrr6o06Z6iDsAAADwKQUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIgFQ/Zg2+6ioqKlLb9+jRo1PbNwAAsOGsoAMAAEAGKOgAAACQAQo6AAAAZICCDgAAABmgoAMAAEAGKOgAAACQAQo6AAAAZICCDgAAABmgoAMAAEAGKOgAAACQAQo6AAAAZICCDgAAABmgoAMAAEAGKOgAAACQAQo6AAAAZICCDgAAABmgoAMAAEAGKOgAAACQAQo6AAAAZICCDgAAABmgoAMAAEAGKOgAAACQAQo6AAAAZICCDgAAABmgoAMAAEAGKOgAAACQAQo6AAAAZICCDgAAABmgoAMAAEAGKOgAAACQAQo6AAAAZICCDgAAABmgoAMAAEAGKOgAAACQAQo6AAAAZICCDgAAABmgoAMAAEAGKOgAAACQAQo6AAAAZICCDgAAABmgoAMAAEAGKOgAAACQAQo6AAAAZICCDgAAABmgoAMAAEAGKOgAAACQAQo6AAAAZICCDgAAABmgoAMAAEAGKOgAAACQAQo6AAAAZICCDgAAABmgoAMAAEAGKOgAAACQAQo6AAAAZICCDgAAABlQlvYAwFdTRUVFqvsfPXp0qvsHAIANZQUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADUi/oDz/8cOy0007RqlWrOOKII+K9995LeyQAAACod6kW9JUrV8bgwYNj3Lhx8e6770bLli3jF7/4RZojAQAAQCpSLejz58+Pxo0bR79+/aJhw4YxePDgePHFF9McCQAAAFJRlubOt91222jSpElMnz49+vTpE/fee28ceOCBn/vYysrKqKysjIiIhQsXxhNPPFGPk8LG6dSpU2r7TvvvSJrZI9LPDwAAGyqXJEmS5gB/+MMfYtCgQbHFFltEp06d4sUXX4yWLVt+6ff06tUrZs+eXU8TwsarqKhIbd+jR49Obd8R6WaPSD8/AAB8kS/qtKke4r5o0aL4wQ9+EH/9619j1apVMWLEiDj22GPTHAkAAABSkWpB/8tf/hI777xz7L333tGwYcM455xzYvr06fHJJ5+kORYAAADUu1QLeo8ePeLFF1+Ml156KZIkiTvuuCO23377aNKkSZpjAQAAQL1L9SJxO++8c1x77bUxaNCgWLp0afTo0SOmTJmS5kgAAACQilQLekTE0KFDY+jQoWmPAQAAAKlK9RB3AAAA4FMKOgAAAGSAgg4AAAAZoKADAABABijoAAAAkAEKOgAAAGSAgg4AAAAZoKADAABABijoAAAAkAEKOgAAAGSAgg4AAAAZoKADAABABijoAAAAkAEKOgAAAGSAgg4AAAAZoKADAABABijoAAAAkAEKOgAAAGSAgg4AAAAZoKADAABABijoAAAAkAEKOgAAAGSAgg4AAAAZoKADAABABijoAAAAkAEKOgAAAGSAgg4AAAAZoKADAABABijoAAAAkAEKOgAAAGSAgg4AAAAZoKADAABABijoAAAAkAEKOgAAAGSAgg4AAAAZoKADAABABijoAAAAkAEKOgAAAGSAgg4AAAAZUJbvAxcuXBivv/561NbWRkTE2rVrY+HChXHaaacVbTgAAAAoFXkV9P/5n/+JkSNHRm1tbeRyubrtDRo0UNABAACgAPIq6BdeeGGMGDEizj777Nh5551j6tSpMW3atGjYsGGx5wMAAICSkFdBX758eRx88MGx4447xlZbbRVbbrllDBw4ME488cS45pprij0jAAAAGVdRUZHavkePHp3avgspr4J+3HHHxfDhw+Pxxx+PvfbaK84999xo2rRplJeXF3s+AAAAKAl5XcX95ptvjpNPPjnWrl0bN910U7Ru3Tpqamrit7/9bbHnAwAAgJKQ1wp6o0aNYuzYsXW3H3vssaINBAAAAKUor4JeXl6+3tXb/9PixYsLOhAAAACUorwK+ogRIyKXy0VtbW1ccsklcfrpp0fHjh2LPRsAAACUjLwK+gUXXBARETU1NXHJJZfEiBEjYrfddivmXAAAAFBS8iro1dXVERFRW1sbERFr1qyp29aoUaMijQYAAAClI6+CvuWWW653Dnrv3r3r/ryutAMAAAAbL6+Cfvvtt3/hReIAAACATZdXQR82bFh88sknMXPmzKiqqoqOHTvGvvvuG2VleX07AAAA8F/k1bBfeumlOPzww2PhwoWRJElERHTt2jUeeOCB6N69e1EHBAAAgFKwRT4PGjlyZHTp0iXmzJkTH3zwQcyZMyc6d+4cI0aMKPZ8AAAAUBLyWkF/4YUXYsqUKfGtb30rIiJ69uwZP/vZz+LYY48t6nAAAABQKvJaQd9hhx1iwoQJsWLFioiI+PDDD2PixImxyy67FHU4AAAAKBV5raBfd911ceSRR0abNm2iVatWsXz58mjRokU8/PDDxZ4PAAAASkJeBf073/lOvPnmm/HAAw/EkiVLolOnTjFw4MBo1apVsecDAACAkpBXQX/00UcjIqJjx47RsWPHiIh49tlnIyKif//+RRoNAAAASkdeBX3AgAGRy+Xqbq/7qLVcLhe1tbXFmQwAAABKSF4XiausrIyOHTtGp06d4vbbb4+5c+fG3Llz46233ir2fAAAAFAS8irop512Wvzzn/+MH/7wh/HTn/40fvCDH8T7778fXbp0KfZ8AAAAUBLyXkGfOHFiNG3aNM4999z4xz/+Eb169YoTTjih2PMBAABAScjrHPQzzjjjc7dPmTIlJk+eXNCBAAAAoBTltYL+6quvxscffxxr165d78sF4gAAAKAw8lpB32WXXeLpp5+Ovffeu9jzAABs1ioqKlLd/+jRo1PdPwAbL68V9CRJ6j5aDQAAACi8vFbQIyKmTp0af//739fblsvl4vTTTy/4UAAAAFBq8i7oY8eO/cw2BR0AAAAKI6+Cvnbt2mLPAQAAACUtr3PQq6ur48orr4zevXtH165d4+WXX47LL788Xn311WLPBwAAACUhrxX0M888Mx588MEYPHhwXHfddbFmzZpYsmRJDB8+PP785z8Xe0YA2Ky4ijcAsDHyWkH//e9/H7fcckuMHTu27mruAwcOjDlz5hR1OAAAACgVeRX0Nm3axIwZM9b7qLWpU6fGdtttV7TBAAAAoJTkdYj7FVdcEUOGDIk777wzIiIGDBgQy5cvj/vuu6+owwEAAECpyKugH3PMMdG9e/f43//931i0aFF8/etfj+OOOy523nnnYs8HAAAAJSHvz0Hv1KlT7LHHHrF06dJo165ddOrUqZhzAQAAmxkXyYRNk1dBf+ihh+LEE0+MFStW1J2H3rJly7jnnntiwIABBRlk0qRJcdVVV8XKlSvjX//6V0GeEwAAADYXeRX0s88+O/bee++44YYbonPnzjFv3rwYNWpUnHnmmQUp03fddVdceOGFMX78+Nh77703+fkAAADqmyMI2FR5XcX9o48+irPOOiu23XbbaNiwYWy//fZx5plnxsqVKwsyxAUXXBATJ06M73znO1FWlvdR9wAAAPCVkVcbPuyww+KGG25Yrzxfd911ccABB8Sjjz5at61///4bPMCCBQti0aJFcdttt8XRRx8d2223Xdx+++2xww47bPBzAQAAwOYql/znh5t/gS22+O8L7blcLmprazd4gGeeeSb22WefGD9+fAwePDiuuOKKePDBB+PZZ59d73GVlZVRWVkZERELFy6MyZMnb/C+oL698847qe27ffv2qe07It3sEennp7R5/Zc2P39KWam//uUv3fe+G2r06NExe/bsz2zPq6DPnz8/r5106dJlgwf7y1/+Eqeeemq89tprERGxatWqaNq0abz//vvRokWLz/2eXr16fW4YyJo0z0NK+xwk52BRyrz+S5ufP6Ws1F//8pfue98N9UWdNq9D3DemeOerc+fOUVVVFTU1NVFWVha5XC4i8lu1BwAAgK+K1Ftwp06dokePHnHllVfGmjVr4je/+U3stdde0axZs7RHAwAAgHqTekGPiLj77rvj8ccfj7Zt28YjjzwSd9xxR9ojAQAAQL3aoM80W7FiRVx88cXx6quvRq9eveJnP/tZNGnSZJOH6Ny5czz22GOb/DwAAACwudqgFfRhw4bFhAkToqysLG644YYYPnx4seYCAACAkrJBK+gPPfRQTJ06Nfr37x9/+MMfYtiwYUUaCwAAAEpL3ivotbW1UV1dHW3bto2IiHbt2sVHH31UtMEAAACglOS1gt67d++6Pw8bNiyaNm0aH374YdGGAmDzVuqfAwsAsDHyKug77rjjev9dp1evXoWfCAAAAEpQXgX9e9/7XvTs2TNatGhR7HkAAACgJOV1DvoBBxwQf//734s9CwAAAJSsvFbQkySJBQsWxBtvvPGZ+3bYYYeCD/VV4jxMAAAA8pH3x6wNGTJkvdtJkkQul4va2tqCDwUAAAClJu+Cfv3118euu+5azFkAAACgZOVd0L/97W+v93FrAAAAQOHkdZG4GTNmRI8ePeL999+PiIgPP/wwVq1aVdTBAAAAoJTkVdAbNGgQ22+/fVx88cUREXHfffdF586d46WXXirqcAAAAFAq8iroZ555Zuyzzz7xk5/8JCIijjjiiOjbt2+cdNJJRR0OAAAASkVeBX3evHlx+umnx9e//vWIiGjdunUMGzYs5s2bV8zZAAAAoGTkdZG4vfbaKy666KJo1KhRlJeXR1VVVVxyySUuGgcAAAAFktcK+m233RZr166Nfv36Rffu3aNfv35RU1MTlZWVxZ4PAAAASkJeK+idOnWKmTNnxvz582Px4sXx9a9/PTp37lzs2QAAAKBk5P056A8++GBMmTIlqqqqomPHjnHiiSfGQQcdVMzZAAAAoGTkdYj79ddfH0cccUS8/PLL0axZs3jxxRdjwIABcfPNNxd7PgAAACgJeRX0a665JsaMGRNz5syJ++67L55//vkYM2ZMXH755cWeDwAAAEpCXgV92bJl0bNnz/W2ffOb34yPP/64KEMBAABAqcnrHPTDDz88zj777Fi4cGF07do15s+fH2PHjo3DDjus2PMBAABASciroN98880xcuTIGD16dFRXV0ejRo1i8ODBcf311xd7PgAAACgJeRX0Fi1axJ133hm33357/Pvf/4527drFFlvkdXQ8AAAAkIe8WvaKFSvi/PPPjyuuuCIiIo444ojo3bt3zJw5s6jDAQAAQKnIawX91FNPjenTp0ezZs3i1ltvjW222SYiIkaOHBlz5swp6oAAAABQCvIq6I899lhMmDAh9thjj/jGN74Rv//97+Pjjz+OQw89tNjzAQAAQEnIq6B/8MEH0b59+2jfvn1ERDRu3Dhqa2tjzZo1RR0OAAAASkVeBT0iYvjw4dG8efOIiBg2bFisXbu2aEMBAABAqcmroA8dOjRyuVxEROy4445123v16lWcqQAAAKDE5FXQJ0yYUOQxAAAAoLTlVdB79+79udtzuVz85S9/KehAAAAAUIryKuhLliyJefPmRZcuXWL//fcv8kgAAABQevIq6G+88Ubceuutcemll8a8efPi8ssvj7322qvYswEAAEDJyKugl5WVxZlnnhnf//7349prr42BAwfGfvvtF5deemnssssuxZ6RzVhFRUWq+x89enSq+wcAAMhXXgW9vLy87iruERG1tbXxxz/+MR588EGfhQ4AAAAFkFdBHzFixHoFHQAAACisvAr6BRdcUOQxAAAAoLTlVdC32GKLz11Bz+VyUVNTU/ChAAAAoNTkVdBvuummuoJeVVUVF110UVx22WXRunXrog4HAAAApSKvgn7GGWfU/fmDDz6Iiy++OAYOHBg9evQo2mAAAABQSvL+HPSIiJqamrj//vujrKwsunTpUtTBAAAAoJTkVdB32mmnyOVykSRJNGrUKCoqKqJFixbFng0AgM1MRUVFqvsfPXp0qvsH2BR5FfQZM2ZERMSWW24ZO+ywg3PPAQAAoMDyKuiPPPLIF9532WWXFWwYAAAAKFVfWtB//vOfxxVXXBFXXXVVrF27Nlq3bh3Nmzevuz+XyynoAAAAUABbfNmdV111VSxYsCD+/ve/x6BBg2LNmjUxbNiwePnll2Pu3Lnx1ltv1decAAAA8JX2pQU9SZL45JNPYscdd4wpU6bEjBkz4q9//Wtss802cd1110V1dXV9zQkAAABfaV96iHvfvn1jhx12iCFDhtRta9OmTWy11Vbx4x//OK655pqYN29esWcEAACAr7wvLejTp0+PiIiqqqr1tnfr1i26detWvKkAAACgxGzQx6wBkB+fAwwAwIb60nPQ11m1alWMHj06unTpEo0aNYquXbvGr371q1izZk2x5wMAAICSkNcK+o9+9KO466674tRTT41u3brFW2+9FePGjYv3338/brzxxmLPCAAAmwVHUAGbIq+C/vvf/z5uvPHGOPnkk+u27b777nHOOeco6AAAAFAAeR3ivsUWW8SHH3643rYPP/wwWrRoUZShAAAAoNTktYI+cuTIGDVqVDz22GPRrVu3mD9/fjzwwANx/vnnF3s+AAAAKAl5FfQxY8ZEx44d484774xXXnklOnXqFLfeemuccsopxZ4PAAAASkJeBf2OO+6I7373u3HaaacVex4AAAAoSXmdg/69730v3njjjWLPAgAAACUrrxX0JEni2WefjY8++ugz9/Xv37/gQwEAAECpyaugR0T85Cc/iSRJ1tuWy+Witra24EMBAABAqcm7oE+ZMiV23333Ys4CAAAAJSvvgt6hQ4fo0qVLMWcBAACAkpXXReLmzp0bnTp1in/9618REVFVVRWLFi0q6mAAAABQSvIq6M8//3zstNNOceONN0ZExKOPPhrbbbddPPbYY0UdDgAAAEpFXoe4//SnP42hQ4fGpZdeGhERQ4YMiTlz5sSIESPin//8Z1EHBAAAgFKQ1wr6smXL4rDDDosmTZpERETDhg2jf//+sWzZsqIOBwAAAKUirxX0gw46KH784x/HO++8E+Xl5VFVVRUVFRU+Ax0AAAAKJK+Cfsstt8QZZ5wRZ5xxRtTU1ERZWVkMGjSo7px0AAAAYNPkVdDff//9+N3vfhe1tbWxdOnSaNeuXTRo0KDYswEAAEDJyKugb7fddtG9e/c48sgj48gjj4zy8vJizwUAbKYqKipS3f/o0aNT3T8AbKy8LhJ3xx13xLe//e24/fbbY88994yOHTvGiBEj4qGHHorVq1cXe0YAAAD4ysuroJ900klxxx13xOLFi+Puu++Oxo0bx2233RaHH354bL311nHyySfHwoULiz0rAAAAfGXldYj7Qw89VPc1f/78aNq0aRx99NHx3e9+N1q3bh1jxoyJI444IubMmVPseQEAAOArKa+Cfthhh0W7du3i8MMPj6OOOir69esXjRo1qrs/l8s53wsAAAA2QV4F/c9//nP07t07crnc594/YMCAGDBgQEEHAwAAgFKSV0HfZ599ij0HAAAAlLS8LhJXH5566qnI5XIxe/bstEcBAACAepeJgl5TUxNnnXVWNGnSJO1RAAAAIBV5HeI+ZMiQL7zv7rvv3uQhrrnmmujdu3esWLFik58LAAAANkd5FfTJkydHz549o0WLFvHnP/85vv3tb0fz5s0LMsDChQvjpptuiueeey6mTZtWkOcEAACAzU0uSZLkvz1oiy22iKeffjr22GOPaNSoUcyePTt22223ggxw7LHHxsEHHxynnXZadO3aNe69997o1avXZx5XWVkZlZWVEfFpqZ88eXJB9l9s77zzTqr7b9++far7lz+9/KWcPUJ++eVPk/zyp0l++dMkf+m+991Qo0eP/tzrr+W1gt6iRYtYvHhxLF68OCIiRo0aFeeff3707dt3k4Z65JFH4u23345TTz31vz52+PDhMXz48IiI6NWrV+y///6btO/6UlFRker+jz/++FT3L396+Us5e4T88sufJvnlT5P88qdJ/tJ971soeV0k7tBDD41TTz019tlnn9h5552jRYsWcdBBB8Xee++9STu/7rrr4oUXXogmTZrElltuGfPnz4999tknJkyYsEnPCwAAAJubvFbQb7vttrj66qvj/fffj1GjRkWnTp3ihRdeiMsuu2yTdv7QQw+td/vLDnEHAACAr7K8CnpZWVmce+65dberq6tjl112iTvvvLNogwEAAEApyaugb7nllpHL5T6zPZfLRU1NTcGGmTdvXsGeCwAAADYneRX0iIhf/OIXsc0228Rpp50W559/fnTt2rWIYwEAAEBpyaug53K5OOSQQ2LPPfeM0047LXr37h0HHXRQsWcDAACAkpHXVdw7deoU9957b0yaNCkiIgYOHBgnn3xyvPbaa0UdDgAAAEpFXivov/71r2PEiBGRJEmceeaZ0adPn7j00ktj1113Leg56AAAAFCq8irop556avTv3z8++OCD6NGjR0REHHPMMZ/5mDQAAABg4+RV0H/5y1/W/fmee+5Z775DDz20sBMBAABACcqroP9nKX/77bejQ4cO0ahRo8jlcnHZZZcVbTgAAAAoFXkV9Llz50ZERE1NTTRq1CgeeOCB2G233Yo6GAAAAJSSvK7ivk4ul1vvvwAAAEBh5LWCPmTIkIiISJIkIj49J71169YREXH33XcXaTQAAAAoHXkV9MWLF9etmvfp0ydWrVoVVVVVRR0MAAAASkleBf2JJ574zLZVq1bF22+/HW+88UZstdVW8Y1vfKPQswEAAEDJyKugP/roo5/Z9sorr8To0aMjImKfffaJp556qrCTAQAAQAnJq6APGDAgcrlc3Tno6+RyuXj88cejZcuWRRkOAAAASkVeBT0iYsqUKbH77rvX3Z41a1Ycf/zx0adPn6IMBgAAAKUk749ZW7JkSSxcuDDWrFkT5eXlUV5eXsy5AAAAoKTkvYJ+1llnRcSnh7U3a9Ys9t1336INBQAAAKUmr4L+6quv1v15+fLl8dRTT8WVV14ZEZ9+RvpOO+0UY8aMKc6EAAAAUALyKug77rjjerf32GOP6NOnT5x77rlRVVUVbdu2LcpwAAAAUCryPsT9b3/7W/zxj3+MRYsWxYUXXhgrV66MqVOnRvPmzYs5HwAAAJSEvC4Sd+2110bv3r3jkUceiTvvvDP+/e9/x9VXXx0/+MEPij0fAAAAlIS8CvpvfvObuPHGG+Nvf/tb3Wehn3766TF16tSiDgcAAAClIq+C/sknn0RZWVnkcrm6bfPnz482bdoUbTAAAAAoJXmdgz5y5MgYOXJkPPDAA5HL5eK8886LGTNmxAUXXFDk8QAAAKA05FXQL7rooujUqVPcfffdse2228aqVati3LhxceqppxZ7PgAAACgJeV/F/fTTT4+TTjopli5dGu3atYsmTZoUcy4AAAAoKXmdg/7WW29F3759o1mzZrHNNttEs2bNol+/fvHWW28Vez4AAAAoCXkV9BNPPDHmzZsXlZWVMW3atLjlllti/vz5cdJJJxV7PgAAACgJeR3i/uqrr8akSZPi8MMPr9vWvn37OOWUU4o2GAAAAJSSvFbQBw0aFE8++WSsWbMmqquro7q6OmbMmBFHH330etsAAACAjZPXCvqUKVNi5cqVcc0119RtS5IkIiLGjx9ft622trbA4wEAAEBpyKugjxs3rthzAAAAQEn7rwV99erV0bFjxzjooIPqtv3pT3+K73znO9G4ceOiDgcAAACl4kvPQX/jjTeie/fuMWDAgPW2H3LIIdGjR4/417/+VdThAAAAoFR8aUEfNWpUtG3bNubMmbPe9lmzZkXbtm3jJz/5SVGHAwAAgFLxpYe4P/PMM3H33XfHt771rfW29+zZM375y1/6mDUAAAAokC9dQW/cuHFUVVV97n3vvfdeUQYCAACAUvSlK+gnnHBCnHvuuVFTUxN77713tGzZMpYvXx4zZ86M8847LwYNGlRfcwIAAMBX2pcW9CuvvDLeeeedOOOMMyKXy9VtT5IkjjjiiLj22muLPiAAAACUgi8t6I0bN4577rknrrzyypgzZ06sWLEimjZtGj179oxtt922vmYEAACAr7z/+jnoERGdO3eOzp07F7ktQOoAABYDSURBVHsWAAAAKFlfepE4AAAAoH4o6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABqRf0iRMnxnbbbRetWrWK/v37x4IFC9IeCQAAAOpdqgX9ueeei3PPPTf++Mc/xrvvvhtdunSJUaNGpTkSAAAApCLVgj537twYNWpUdO/ePRo2bBhDhgyJ119/Pc2RAAAAIBW5JEmStIdY5+KLL46qqqq46aabPnNfZWVlVFZWRkTEwoULY/LkyfU93kZ55513Ut1/+/btU92//OnlL+XsEfLLL3+a5Jc/TfLLnyb5S/e974YaPXp0zJ49+zPby1KY5XPNmTMnKisrY9asWZ97//Dhw2P48OEREdGrV6/Yf//963G6jVdRUZHq/o8//vhU9y9/evlLOXuE/PLLnyb55U+T/PKnSf7Sfe9bKKlfJC4iYsGCBTFo0KCYMGFCdOjQIe1xAAAAoN6lXtCXL18eAwcOjEsuuST69u2b9jgAAACQilQL+po1a+Loo4+Ok08+OU466aQ0RwEAAIBUpVrQH3zwwXjsscfiwgsvjGbNmtV9PfHEE2mOBQAAAPUu1YvEHXXUUZGhi8gDAABAalI/Bx0AAABQ0AEAACATFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADUi/o06dPj1122SVat24dhx9+eLz77rtpjwQAAAD1LtWCvmrVqhg8eHCMGzculixZEltvvXX8+te/TnMkAAAASEWqBf1vf/tbdO7cOQ488MBo3LhxnHPOOfHwww+nORIAAACkIpckSZLWzidPnhwTJ06sK+VLliyJLl26xOrVqz/z2MrKyqisrIyIiNdeey122mmnep01Le+++260bds27TFSI3/p5i/l7BHyyy+//PKXKvnlL9X8pZZ93rx58d57731me1kKs9RZtWpVNGjQoO52WVlZVFdXf+5jhw8fHsOHD6+v0TKjV69eMXv27LTHSI38pZu/lLNHyC+//PLLX6rkl79U85dy9v+U6iHujRs3jpqamrrbtbW1UVaW6r8ZAAAAQCpSLejl5eWxYMGCuttVVVXRoUOHFCcCAACAdDS44IILLkhr5+3bt4+LLroodtlll+jWrVucf/75sd1228URRxyR1kiZtPvuu6c9QqrkL938pZw9Qn755S9l8stfyuQv3fylnH2dVC8SF/Hp56Cfc845sWTJkthvv/1i/Pjx0aZNmzRHAgAAgHqXekEHAAAAUj4HHQAAAPiUgg4AAAAZoKDXs4kTJ8Z2220XrVq1iv79+9ddxX7s2LHRuXPn6NChQ/z4xz+O2traiIj45JNPYtiwYdG2bdvYZpttYuLEiZ95zn//+9/Rtm3bqKioqNcsG6OQ+WfNmhVlZWXRrFmzuq/nn38+lVz5KvTP/9lnn40DDzwwmjdvHm+88Ua959kQhcr+xBNPrPczb9asWTRs2DAuv/zy1LLlo5A/+zfffDP222+/aNGiRey+++7x3HPPpZJpQxQ6f+/evaNFixZxwAEHxPz581PJtCE2NH9ExJw5c2LkyJFx4oknrvdczz//fPTq1StatWoVffr0ibfeeqtes2yMQuZfvXp1TJ48Ofr16xf33XdfvebYWIXM//DDD8euu+4aLVq0iN69e8fLL79cr1k2RiHzT506NXbaaado1apVDBgwIBYtWlSvWTZGIfOv8+abb8aWW24Z9957b71k2BSFzD9lypRo2LDheu8Bli1bVq95NlShf/7Tpk2LPffcM5o1axarV6+utxwbq1D5J06c+Jn3fw0aNIh77rmn3jMVXUK9mT17dtKuXbvk73//e1JdXZ2cdtppyaBBg5KZM2cm3/jGN5L58+cn7777bvLNb34zueeee5IkSZIrrrgiOeSQQ5KVK1cmzz//fNKiRYtkwYIF6z3v8OHDk6ZNmyZXXXVVGrHyVuj8999/f3LEEUekGWmDFDr/66+/nrRt2zaZOHFisnLlyjSj/VfFeu0nSZLU1tYm22yzTfLGG2/Ud6y8FTr/gQcemIwZMyapqalJbrnllmS77bZLM95/Vej8e+65Z3LhhRcm1dXVycUXX5x85zvfSTPef7Ux+c8///xkxx13TA455JBk4MCB6z3fzjvvnEyYMCGprq5Ofv3rXycHH3xwGrHyVuj82267bXLooYcm3bp1S6ZMmZJGpA1SyPwLFy5MWrVqlTz55JNJTU1NcuGFFya77bZbWtHyUuj8rVu3TmbNmpXU1NQkP/7xj5MTTjghrWh5KfTrf53+/fsnTZs2zfzfgULnv/baa5NzzjknjSgbpdD5n3zyyaRDhw7J1KlTk1WrVqURaYMU6/WfJEmyfPnypEOHDskHH3xQX3HqjRX0ejR37twYNWpUdO/ePRo2bBhDhgyJ119/PaZNmxbHHntsdO7cObbeeusYNmxYPPzwwxHx6b+SnXHGGbHVVltFz549Y//994/p06fXPeezzz4bM2fOjO9+97tpxcpbofMvXrw4OnbsmGakDVLo/GPHjo0f/vCHMXTo0Nhqq63SjPZfFeO1v879998f22+/fWy//fb1HStvhc7/8ssvxwknnBANGjSIk08+Of75z3/Gxx9/nGbEL1XI/O+//37MmjUrzj333GjYsGH87Gc/ixdeeCEWL16ccsovtjH5zzrrrHjttdfiuOOOW++55s+fH++8804MHTo0GjZsGD/60Y9i+vTp6608ZE0h80dEPPPMM/H//t//i86dO9d3lI1SyPxz586NoUOHxn777Vf39//1119PI1beCpl/1apVUVFREb169YoGDRrEkUceGS+99FIasfJW6Nd/xKeryLlcLnr16lWfUTZKofOXwnu/L8t/0UUXRUVFRRx++OHRuHHj+o6zwYrx+l/ntttuiyOPPDJatmxZH1HqVVnaA5SSY445Zr3bTz/9dOy3335RVVUV3bp1q9teXl4e06ZNi4iIqqqqaN++/Xr3LVmyJCIi1q5dGyNHjozrr78+xo8fXw8JNk2h8y9evDimT58eHTp0iObNm8dFF10UgwcProckG6fQ+WfMmBHV1dXRtWvXaNy4cd0v7CwqdPb/dO2118bPfvazIk1eGIXOf8ABB8TkyZPj17/+ddxzzz2x5557ZvofaQqZ//8W0YYNG0Z5eXm8/fbbmX3TtjH5t9566899rqqqqmjXrl3kcrmIiGjdunU0bNgwli5dGuXl5UVKsGkKmT8iom3btsUZtEgKmX/fffeNfffd9zPPlWWFzL/tttvGtttuGxGfngYzceLEOOigg4o0eWEU+vX/0UcfxS9+8Yt4+OGH4/TTTy/O0AVU6PyLFy+OqVOnRkVFRZSXl8c111wTffv2Lc7wBVDI/DU1NfH0009Ht27d4txzz422bdvGLbfcEnvttVfxAmyiQv/816mtrY1x48bF1KlTCztwRlhBT8mcOXOisrIyxowZE6tWrYoGDRrU3VdWVlZ3TsmX3XfzzTfHTjvtFH369Knf4QugEPkPOeSQuPzyy2PRokVx6623xumnn75ZnIsZUZj8CxcujGbNmsWrr74aN954Y5x00knx7rvv1m+QjVCI7P/5XIsWLYpDDjmkfoYvgELkHzt2bFxzzTXRuHHjOOOMM+KGG26o3xCbYFPzb7311tGjR4+48sorY82aNVFZWZn56y/8p3zzf5H/+z35fl9WbGr+zV0h87/99ttx3nnnxZVXXlmMUYuiUPlPOeWUaN68efzpT3+KX/7yl8Uat+AKkf/CCy+ME044IdNHjX2RQuQfPHhwXHvttbFkyZL4+c9/Hscdd1wsX768mGMXzKbmf/fdd2P16tXRtWvXupXpY489Nqqrq4s9ekEU8vff/fffH126dIldd921GKOmTkFPwYIFC2LQoEExYcKE6NChQzRu3Dhqamrq7q+trY2GDRtGRHzhfUuXLo2xY8fGVVddVe/zb6pC5I+I6N27dxx77LHRoEGDOPDAA+OAAw6IJ598sn7DbIRC5V+7dm2MGTMmmjRpEv369Ytdd901nnnmmfoNs4EKlX2da665JkaOHBlbbLF5/CorRP4kSeKoo46Kyy+/PFavXh3Tpk2Lo48+Oj744IN6z7OhCvXznzRpUjzwwAPRtWvXeOutt6J58+bRrl27+g2zETYk/xf5v9+T7/dlQSHyb84KmX/58uUxcODAuOSSS6JHjx7FGrmgCpl/4sSJsXLlyjjppJO+8CJqWVOI/K+88kr84Q9/2Kz+UWKdQv38Dz300Dj44IOjQYMGMWTIkOjYsWPMmTOnmKMXRCHyr127Nho3bhznnXdeNGrUKIYNGxZr166N1157rdjjb7JC//6/9tpr46yzzirGqJmwebyr/Qr5z/+prjskp7y8vO6KhhGfHsLYoUOHL71v/PjxdYeHbLnlljFp0qT4xS9+Ed///vfrN9AGKlT+iIirr756vfNO1x3ymWWFzN+5c+d4++2313v+/7uyliWFzL7u9oMPPpj51/w6hcr/7rvvxksvvRQ/+MEPoqysLPr27Rvt27ePmTNn1m+gDVTIn3+PHj1i9uzZsWjRohg2bFg0bdp0vUPlsmhD83+R8vLyqKqqqjvU/4MPPog1a9Zk/rDvQuXfXBUy/5o1a2LQoEExePDgGDp0aNFmLqRC5f/Xv/4VDz74YER8+o9VI0aMiL/+9a/FG7xACpV/3Lhx8fbbb0ebNm1iyy23jKeeeiqGDBkSF154YVHn31SFfP2PGTMmPvnkk7rbX8X3fl+kQ4cOsXbt2li6dOl627P83i+i8L//n3vuuZg/f/5mcf2tjZb2VepKSXV1ddK3b99k7Nix622fOXNm0q5du+TNN99Mli1blvTs2TOZNGlSkiSfXsm4T58+yYoVK5KXXnopadmyZTJ37tzPPPcpp5yS+au4Fzr/aaedlowcOTKprq5OZs2alTRv3jx588036ztW3gqd/5e//GVy2GGHJStXrkxmzJiRtG7dOnnvvffqO1ZeivHaP++885LTTz+9PmNstELmX7t2bdKxY8dk4sSJydq1a5Nnn302admyZTJv3rw0ouWlGD//2tra5IUXXkh69eqVVFRU1GecDbYx+dcZP378517Ffdy4ccmaNWuSCy64IOnbt2/RM2yKQudfp0+fPpm/gnWSFD7/0KFDk5EjRxZ97kIpZP5//OMfSZs2bZKXX345qa2tTS699NLMf4pDsV7/SbJ5/B0odP5+/foll19+eVJbW5s8+OCDSevWrTN9Fe9C5x8yZEgyYsSIZPXq1cmkSZOSLl26JNXV1UXPsbGK8fo/8cQTk0svvbSoc6dNQa9H9913XxIRSdOmTdf7mjFjRjJ27Njk61//etK+fftk9OjRSW1tbZIkSfLxxx8np5xySvK1r30t2WabbZI777zzc597cyjohc6/bNmy5Oijj05atWqVdOvWLbnrrrvSipaXQuf/5JNPklNPPTX52te+luy4447JtGnT0or2XxUj+9Zbb528+OKLaUXaIIXO/7e//S3ZY489kubNmyfbb7998rvf/S6taHkpxu++bt26JTvuuGNy3XXXpRFpg2xM/nU+7w3KnDlzkt122y1p0aJF0qdPn0z/40ySFD7/OptDOUmSwuafM2dOEhHJVltttd5zTZgwob5j5a3QP/+JEycm22yzTdKyZcukb9++yT//+c/6jLPBivX6T5LN4+9AofPPmzcv6devX9KiRYtkl112SaZPn16fcTZYofMvW7YsOeqoo5JWrVolu+22WzJr1qz6jLPBCp1/8eLFSfPmzZOlS5fWZ4x6l0uSJElh4R4AAAD4D85BBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAErEvHnzIpfLfeZr5syZaY8GAEREWdoDAAD1q6KiIvbcc8+62927d09xGgBgHSvoAFBiunfvHvvuu2/dV7NmzeKiiy6K9u3bR9u2beOMM86Ijz/+uO7xJ5xwwnor7nvttVeK0wPAV5eCDgAl7re//W1cfPHF8atf/SoqKirirrvuil/96lfrPaZnz57x5z//OQ455JCUpgSArz6HuANAiZs0aVIcdthhcfbZZ0dExPPPPx9TpkyJq6++uu4xbdq0iX333TfatWsX//73v9MaFQC+0qygA0CJW7JkSXTr1q3udrdu3aKqqqru9vLly6N9+/ZpjAYAJUVBB4AS16lTp5g/f37d7blz50bHjh0jImLVqlUxa9YsF5IDgHqgoANAiTvppJPigQceiBtvvDEmTZoU48ePjxNPPDGWL18eP/3pT2PZsmWx/fbbx9NPPx1Lly6NDz/8MF5//fW0xwaArxznoANAiTvllFNi0aJFccUVV8SKFSti8ODBccEFF8QzzzwT48aNi4iI448/fr3vOf/882Py5MlpjAsAX1m5JEmStIcAALLniSeeiAMOOCBeffXV2Gmnneq277///tGhQwcFHQAKzAo6APC5WrZsGfvss09stdVW623v0aNHfO1rX0tpKgD46rKCDgAAABngInEAAACQAQo6AAAAZICCDgAAABmgoAMAAEAGKOgAAACQAQo6AAAAZMD/B/PQo5tNQ9BZAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 1008x504 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.figure(figsize = (14,7), facecolor = 'w')\n",
    "\n",
    "plt.bar([i for i in range(2004, 2018)], sustain, width=.5, color = colors['grey'])\n",
    "plt.xticks([i for i in range(2004, 2018)], [i for i in range(2004, 2018)], fontproperties = regluar_font)\n",
    "plt.yticks(fontproperties = regluar_font)\n",
    "plt.grid(axis = 'y')\n",
    "plt.ylim(0,10)\n",
    "plt.ylabel('Средняя устойчивость региона',  fontproperties = medium_font)\n",
    "plt.xlabel('Год', fontproperties = medium_font)\n",
    "plt.tight_layout()\n",
    "plt.savefig('analysis/percolation_regions/plots_v4/Mean Sustainability.png')\n",
    "# plt.yticks([i for i in range(len(sustain))], [i for i in range(2004, 2018)])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_list = {year : gpd.read_file(f'analysis/percolation_regions/{year} region cores sustain_v2.gpkg') for year in range(2004,2018)}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None]"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "[\n",
    "    df_list[year].dropna(\n",
    "        subset = ['parent']\n",
    "    ).dissolve(by = 'parent').reset_index().to_file(\n",
    "        f'analysis/percolation_regions/{year} region cores sustain_v2.gpkg'\n",
    "    ) for year in range(2004,2018)\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None]"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "[\n",
    "    bounds.drop(\n",
    "        columns = ['parent', 'sustain']\n",
    "    ).merge(\n",
    "        i, on = 'NAME', how = 'right'\n",
    "    ).dropna(subset = ['geometry']).dissolve(by = ['parent','percolation_threshold']).reset_index().to_file(\n",
    "        f'analysis/percolation_regions/evo/{i.year.unique()[0]}_evolution_v2.gpkg',\n",
    "        driver = 'GPKG'\n",
    "    ) for i in percolation_regions\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None]"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "[\n",
    "    bounds.drop(\n",
    "        columns = ['parent', 'sustain']\n",
    "    ).merge(\n",
    "        i, on = 'NAME', how = 'right'\n",
    "    ).dropna(subset = ['geometry']).dissolve(by = ['parent','percolation_threshold']).reset_index().to_file(\n",
    "        f'analysis/percolation_regions/evo/{i.year.unique()[0]}_evolution_v2.gpkg',\n",
    "        driver = 'GPKG'\n",
    "    ) for i in percolation_regions\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.\n",
      "  \"\"\"Entry point for launching an IPython kernel.\n"
     ]
    }
   ],
   "source": [
    "pd.Series([f'percolation_{eps}' for eps in epses]).rename('percolation_threshold').to_csv('analysis/percolation_regions/evo/Atlas.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
