{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Percolational regions as a polycentricity measure"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "import os\n",
    "import pandas as pd\n",
    "import geopandas as gpd\n",
    "import numpy as np\n",
    "from sklearn.cluster import DBSCAN"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "os.chdir('D:/bachelors/datasets/')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Preparation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('Variables/mappers/communes_names_map.json') as infile:\n",
    "    names_map = json.load(infile)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "nodes_path = 'analysis/yearly_graphs_v4/total/nodes_total_{}.csv'\n",
    "datatables_path = 'translated_data_v4/data_{}.csv'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def read_raw_data(datatable_path):\n",
    "    df_current = pd.read_csv(datatable_path)\n",
    "#     df_current['geo_departure'], df_current['geo_arrival'] = df_current['geo_departure'].map(names_map), df_current['geo_arrival'].map(names_map)\n",
    "    df_current.dropna(subset = ['geo_departure', 'geo_arrival'], inplace = True)\n",
    "#     df_current = df_current[df_current.geo_departure != df_current.geo_arrival]\n",
    "    df_current = pd.pivot_table(df_current, 'uid_person', 'geo_departure', 'geo_arrival', aggfunc = 'nunique')\n",
    "    df_current.values[[np.arange(df_current.shape[0])]*2] = 0\n",
    "    maxim = np.max(df_current.fillna(0).values)\n",
    "    df_current = ((df_current / maxim) * -1 + 1).fillna(1)\n",
    "    \n",
    "    return df_current"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Create a list of epsilon values to cluster"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "epses = [float(i[:4]) for i in np.arange(0.1, 1.01, 0.01).astype(str).tolist()] "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "epses = [i/100 for i in range(1, 101)]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Plot tools"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "from matplotlib import font_manager as fm\n",
    "import matplotlib\n",
    "\n",
    "medium_font = fm.FontProperties(fname =  \"D:/bachelors/datasets/viz/Roboto-Medium.ttf\", size = 12)\n",
    "regluar_font = fm.FontProperties(fname = \"D:/bachelors/datasets/viz/Roboto-Regular.ttf\", size = 12)\n",
    "\n",
    "colors = {\n",
    "    'peach' : '#FCB886',\n",
    "    'blue' : '#6FC7F7',\n",
    "    'green' : '#78AF34',\n",
    "    'red' : '#D25B5B',\n",
    "    'grey' : '#8B8B8B'\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "def model_regions(dat):\n",
    "    \"\"\"Builds hierarchy of regions for a distance matrix\"\"\"\n",
    "    series_list = []\n",
    "    for eps in epses:\n",
    "        labs = DBSCAN(eps = eps, min_samples = 2, metric = 'precomputed').fit(dat).labels_\n",
    "        series_list.append(pd.Series(labs, dat.index).rename(f'percolation_{eps}'))\n",
    "    percolation_classes = pd.DataFrame(series_list).transpose()\n",
    "    percolation_classes = percolation_classes.applymap(lambda elem: None if elem == -1 else elem)\n",
    "    return percolation_classes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "def map_series(series):\n",
    "    if series.name in dict_perc_reg.keys():\n",
    "        return series.map(dict_perc_reg[series.name])\n",
    "    else:\n",
    "        return series"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('Variables/mappers/communes_names_toRussian_map.json') as infile:\n",
    "    rus_names = json.load(infile)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_percolation(matrix, year):\n",
    "    plt.figure(figsize = (11,11))\n",
    "\n",
    "    ax = sns.heatmap(matrix,\n",
    "                     linewidths = .3,\n",
    "                     zorder = 1,\n",
    "                     cmap = 'viridis',\n",
    "                     cbar = False)\n",
    "    plt.grid(ls = ':', zorder = 0)\n",
    "    plt.xticks(fontproperties = regluar_font)\n",
    "\n",
    "    plt.yticks(fontproperties = regluar_font)\n",
    "    ax.set_title(f'{year}', loc = 'left', fontproperties = medium_font, fontsize=24)\n",
    "    ax.set_xlabel('Фильтр интенсивности поездок', fontproperties = medium_font, fontsize=18)\n",
    "    ax.set_ylabel('Главный муниципалитет кластера', fontproperties = medium_font, fontsize=18)\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(f'analysis/percolation_regions/plots_v4/{year}_percolation.png')\n",
    "    plt.close('all')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "\n",
    "def round_down(n, decimals=0):\n",
    "    multiplier = 10 ** decimals\n",
    "    return math.floor(n * multiplier) / multiplier"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "bounds = gpd.read_file('../qgis/base/Netherlands_communes.gpkg')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "from collections import defaultdict"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "def percolation_regions_resample(percolation_classes, year):\n",
    "    df = percolation_classes.drop(columns = ['flow_cent']).stack().reset_index().rename(columns = {\n",
    "        'commune' : 'NAME',\n",
    "        'level_1' : 'percolation_threshold',\n",
    "        0 : 'parent'\n",
    "    }).assign(\n",
    "        year = year\n",
    "    )\n",
    "    \n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n",
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.\n",
      "  import sys\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    }
   ],
   "source": [
    "sustain = []\n",
    "regions_cores_list = []\n",
    "region_to_core_map = defaultdict(dict)\n",
    "percolation_regions = []\n",
    "for year in range(2004,2018):\n",
    "    dat = read_raw_data(datatables_path.format(year))\n",
    "    nodes = pd.read_csv(nodes_path.format(year))\n",
    "    \n",
    "    percolation_classes = model_regions(dat)\n",
    "    percolation_classes = percolation_classes.reset_index().merge(nodes[['commune', 'flow_cent']], left_on = 'geo_departure', right_on = 'commune', how = 'left').drop(columns = ['geo_departure'])\n",
    "    dict_perc_reg = {\n",
    "        f'percolation_{eps}' : percolation_classes.set_index(\n",
    "            'commune'\n",
    "        ).groupby(\n",
    "            f'percolation_{eps}'\n",
    "        )['flow_cent'].idxmax().to_dict() for eps in epses\n",
    "    }\n",
    "    percolation_classes = percolation_classes.apply(map_series).apply(\n",
    "        lambda x: x.map(rus_names) if x.name not in ['commune', 'flow_cent'] else x\n",
    "    )\n",
    "\n",
    "    matrix = percolation_classes.drop(columns = ['flow_cent', 'commune']).apply(lambda column: column.value_counts())\n",
    "    percolation_classes = percolation_classes.set_index('commune')\n",
    "    percolation_regions.append(percolation_regions_resample(percolation_classes, year))\n",
    "    matrix.columns = [float(i.split('_')[1]) for i in matrix.columns]\n",
    "    matrix = matrix.sort_values(by = list(matrix.columns))\n",
    "    first_value = matrix.dropna(axis=1, how = 'all').columns[0]\n",
    "    matrix = matrix.loc[:, round_down(first_value, 1):]\n",
    "#     break\n",
    "    matrix = matrix.assign(\n",
    "        order = matrix.apply(lambda row: row.loc[row == row.dropna().iloc[0]].index[0], axis = 'columns'),\n",
    "        parent = matrix.apply(\n",
    "            lambda row: round(row.loc[row == row.dropna().iloc[-1]].index[0] + .01, 2) if \\\n",
    "            row.loc[row == row.dropna().iloc[-1]].index[0] < 1 else 1,\n",
    "            axis = 'columns'),\n",
    "        duration = matrix.apply(lambda x: x.isnull().sum(), axis='columns')\n",
    "    )\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "#     matrix['order'] = matrix.apply(lambda row: row.loc[row == row.dropna().iloc[0]].index[0], axis = 'columns')\n",
    "#     matrix['duration'] = matrix.apply(lambda x: x.isnull().sum(), axis='columns')\n",
    "#     matrix['parent'] = matrix.apply(lambda row: row.loc[row == row.dropna().iloc[-1]].index[0] + .01, axis = 'columns')\n",
    "    matrix = matrix.sort_values(by = ['order', 'duration'])\n",
    "    plot_percolation(matrix.drop(columns = ['order', 'duration', 'parent']), year)\n",
    "    \n",
    "    cutpoint_core = matrix['order'].to_dict()\n",
    "    parent_core = matrix['parent'].to_dict()\n",
    "    matrix.drop(columns = ['order', 'parent', 'duration'], inplace = True)\n",
    "#     break\n",
    "    sustain.append(len(matrix.columns) - matrix.isna().sum(axis = 'columns').mean())\n",
    "    regions_cores = {}\n",
    "    for name, cpt in cutpoint_core.items():\n",
    "        regions_cores.update(\n",
    "            percolation_classes[percolation_classes[f'percolation_{cpt}'] == name][f'percolation_{cpt}'].to_dict()\n",
    "        )\n",
    "        \n",
    "    parent_cores = {}\n",
    "    for name, cpt in parent_core.items():\n",
    "        parent_cores.update(\n",
    "            percolation_classes[percolation_classes[f'percolation_{cpt}'] == name][f'percolation_{cpt}'].to_dict()\n",
    "        )\n",
    "\n",
    "    \n",
    "    sustainability = percolation_classes.drop(columns = ['flow_cent']).apply(\n",
    "        lambda x: x.value_counts(), axis = 'rows'\n",
    "    ).dropna(how = 'all').dropna(axis = 'columns', how = 'all')\n",
    "    sustainability['sust'] = sustainability.apply(lambda x: sustainability.shape[1] - x.isnull().sum(), axis='columns')\n",
    "    \n",
    "    bounds['parent'] = bounds['NAME'].map(regions_cores)\n",
    "    bounds['sustain'] = bounds['parent'].map(sustainability['sust'].to_dict())\n",
    "    bounds.to_file(f'analysis/percolation_regions/{year} region cores sustain_v2.gpkg', driver = 'GPKG')\n",
    "    \n",
    "    region_to_core_map[str(year)] = regions_cores    \n",
    "    regions_cores_list.append(bounds.assign(core = lambda frame: frame.NAME.map(regions_cores), \n",
    "                                            year = year))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAA+gAAAHwCAYAAAA1uUU7AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjMsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+AADFEAAAgAElEQVR4nO3deZSVBf0/8M+VAUR2kmUoNveNIuWooYkKIoqaopYgIv1UMDSzmuxbJu4bTqKFqfM1BXGhL2YFfJUiw8oSBXHLDVNAlkGUFBSFYYbn94eHOfF16QL3zvPAfb3OmSP3uXfu83mfe2e873m2XJIkSQAAAACp2iHtAQAAAAAFHQAAADJBQQcAAIAMUNABAAAgAxR0AAAAyAAFHQAAADJAQQcAAIAMaLCC/v7778cdd9wRBx98cDz11FMREVFXVxcVFRVRXl4eXbp0ieuuu66hxgEAAIBMKWuIlbz//vvRvXv36NevX8yfPz+SJImIiAceeCD+9Kc/xQsvvBCrV6+OQw45JA4//PA4+OCDG2IsAAAAyIwGKejNmjWLV199Ndq2bRvdu3evXz5jxowYMWJEtGvXLtq1axennHJKPPzwwwo6AAAAJadBCnqjRo2ibdu2H1teXV0dAwcOrL9dXl4eCxYs+MTnqKqqiqqqqoiIePHFF6NLly7FGRYAAACKaOXKlfH2229/bHmDFPRPs3bt2mjUqFH97bKysli3bt0nPnbkyJExcuTIiIjo3bt3zJ07t0FmBAAAgELq3bv3Jy5P9SzuTZs2jdra2vrbdXV10bhx4xQnAgAAgHSkWtDLy8tj8eLF9berq6ujU6dOKU4EAAAA6Ui1oB9zzDFx1113xYoVK+KNN96IBx54II4++ug0RwIAAIBUpHoM+imnnBJz5syJL37xi9G4ceO48MIL49BDD01zJAAAAEhFLtl4UfJtiJPEAQAAsK36tE6b6i7uAAAAwEcUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAPK0h4AtmeVlZWprbuioiK1dQMAAJvPFnQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIgLK0BwC2T5WVlamuv6KiItX1AwDA5rIFHQAAADJAQQcAAIAMUNABAAAgAxR0AAAAyAAFHQAAADJAQQcAAIAMUNABAAAgAxR0AAAAyAAFHQAAADJAQQcAAIAMUNABAAAgAxR0AAAAyAAFHQAAADJAQQcAAIAMUNABAAAgAxR0AAAAyAAFHQAAADJAQQcAAIAMUNABAAAgAxR0AAAAyAAFHQAAADJAQQcAAIAMSL2gP/zww7HXXntFmzZt4oQTToi333477ZEAAACgwaVa0NesWRNDhgyJ8ePHx1tvvRWtW7eOH/3oR2mOBAAAAKlItaAvWrQomjZtGv3794/GjRvHkCFD4tlnn01zJAAAAEhFWZor33XXXaNZs2Yxc+bM6Nu3bzzwwANx5JFHfuJjq6qqoqqqKiIilixZEo8++mgDTgpbpkuXLqmtO+2fkTSzR6SfHwAANlcuSZIkzQF+85vfxODBg2OHHXaILl26xLPPPhutW7f+zO/p3bt3zJ07t4EmhC1XWVmZ2rorKipSW3dEutkj0s8PAACf5tM6baq7uC9dujS+9a1vxd///vdYu3ZtjBo1Kk499dQ0RwIAAIBUpFrQ//a3v8Xee+8dX/nKV6Jx48ZxwQUXxMyZM+PDDz9McywAAABocKkW9J49e8azzz4bzz33XCRJEnfffXfsvvvu0axZszTHAgAAgAaX6kni9t5777jpppti8ODBsWLFiujZs2dMmTIlzZEAAAAgFakW9IiI4cOHx/Dhw9MeAwAAAFKV6i7uAAAAwEcUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyoCzfBy5ZsiReeeWVqKuri4iIDRs2xJIlS+Lss88u2nAAAABQKvIq6P/93/8do0ePjrq6usjlcvXLGzVqpKADAABAAeRV0C+//PIYNWpUfPvb34699947pk6dGjNmzIjGjRsXez4AAAAoCXkV9FWrVsXRRx8de+65Z+y0006x4447xqBBg+L000+PcePGFXtGAAAAMq6ysjK1dVdUVKS27kLKq6B//etfj5EjR8af/vSnOPjgg+Oiiy6K5s2bR3l5ebHnAwAAgJKQ11ncb7311jjjjDNiw4YN8Ytf/CLatm0btbW18ctf/rLY8wEAAEBJyGsLepMmTWLs2LH1tx955JGiDQQAAAClKK+CXl5evsnZ2//dsmXLCjoQAAAAlKK8CvqoUaMil8tFXV1dXHXVVXHOOedE586diz0bAAAAlIy8Cvpll10WERG1tbVx1VVXxahRo2L//fcv5lwAAABQUvIq6DU1NRERUVdXFxER69evr1/WpEmTIo0GAAAApSOvgr7jjjtucgx6nz596v+9sbQDAAAAWy6vgn7nnXd+6kniAAAAgK2XV0EfMWJEfPjhhzF79uyorq6Ozp07x6GHHhplZXl9OwAAAPAf5NWwn3vuuTj++ONjyZIlkSRJRER07949pk2bFvvuu29RBwQAAIBSsEM+Dxo9enR069Yt5s2bF++++27MmzcvunbtGqNGjSr2fAAAAFAS8tqC/swzz8SUKVPiS1/6UkRE9OrVK374wx/GqaeeWtThAAAAoFTktQV9jz32iAkTJsTq1asjIuK9996LiRMnxj777FPU4QAAAKBU5LUF/eabb46vfe1r0a5du2jTpk2sWrUqWrVqFQ8//HCx5wMAAICSkFdB/+pXvxqvvvpqTJs2LZYvXx5dunSJQYMGRZs2bYo9HwAAAJSEvAr6H/7wh4iI6Ny5c3Tu3DkiIp588smIiBgwYECRRgMAAIDSkVdBHzhwYORyufrbGy+1lsvloq6urjiTAQAAQAnJ6yRxVVVV0blz5+jSpUvceeedsWDBgliwYEG8/vrrxZ4PAAAASkJeBf3ss8+Of/7zn/Gd73wnfvCDH8S3vvWteOedd6Jbt27Fng8AAABKQt5b0CdOnBjNmzePiy66KF588cXo3bt3nHbaacWeDwAAAEpCXsegn3vuuZ+4fMqUKTF58uSCDgQAAAClKK8t6C+99FJ88MEHsWHDhk2+nCAOAAAACiOvgr7PPvvE008/XexZAAAAoGTltYt7kiT1l1YDAODTVVZWprr+ioqKVNcPwJbLq6BHREydOjX+8Y9/bLIsl8vFOeecU/ChAAAAoNTkXdDHjh37sWUKOgAAABRGXgV9w4YNxZ4DAAAASlpeBb2mpibGjRsXv/vd72LZsmUxbdq0mD59epx44omx9957F3tGAABgG+AcDLB18iro5513XkyfPj2GDBkSN998c6xfvz6WL18eI0eOjL/+9a/FnhEAtik+oAIAWyKvy6z9+te/jttuuy3Gjh1bfzb3QYMGxbx584o6HAAAAJSKvAp6u3btYtasWZtcam3q1Kmx2267FW0wAAAAKCV57eJ+3XXXxdChQ+Oee+6JiIiBAwfGqlWr4sEHHyzqcAAAAFAq8irop5xySuy7777xP//zP7F06dL4/Oc/H1//+tedIA4AAAAKJO/roHfp0iUOPPDAWLFiRXTo0CG6dOlSzLkAAACgpORV0B966KE4/fTTY/Xq1fXHobdu3Truv//+GDhwYEEGmTRpUtxwww2xZs2aeO211wrynAAAAA3FVTzYWnmdJO7b3/52fOUrX4n58+fHunXr4pVXXok+ffrEeeedV5Ah7r333rj88svjlltuiVdeeaUgzwkAAADbkrwK+vvvvx/nn39+7LrrrtG4cePYfffd47zzzos1a9YUZIjLLrssJk6cGF/96lejrCzvve4BAABgu5FXGz7uuOPi5z//+Sbl+eabb44jjjgi/vCHP9QvGzBgwGYPsHjx4li6dGnccccdcfLJJ8duu+0Wd955Z+yxxx6b/VwAAACwrcol/35x80+xww7/eUN7LpeLurq6zR7g8ccfj0MOOSTuuuuuGDJkSFx33XUxffr0ePLJJzd5XFVVVVRVVUVExJIlS2Ly5MmbvS5oaG+++WZq6+7YsWNq645IN3tE+vkpbd7/pc3rTykr9fe//KX72XdzVVRUxNy5cz+2PK+CvmjRorxW0q1bt80e7G9/+1ucddZZ8fLLL0dExNq1a6N58+bxzjvvRKtWrT7xe3r37v2JYSBr0jxRSNonCXGSFEqZ939p8/pTykr9/S9/6X723Vyf1mnz2sV9S4p3vrp27RrV1dVRW1sbZWVlkcvlIiK/rfYAAACwvUi9BXfp0iV69uwZ119/faxfvz5++tOfxsEHHxwtWrRIezQAAABoMKkX9IiI++67L/70pz9F+/bt4/e//33cfffdaY8EAAAADWqzrmm2evXquPLKK+Oll16K3r17xw9/+MNo1qzZVg/RtWvXeOSRR7b6eQAAAGBbtVlb0EeMGBETJkyIsrKy+PnPfx4jR44s1lwAAABQUjZrC/pDDz0UU6dOjQEDBsRvfvObGDFiRJHGAgAAgNKS9xb0urq6qKmpifbt20dERIcOHeL9998v2mAAAABQSvLagt6nT5/6f48YMSKaN28e7733XtGG2p6U+rUQgdLkdx8AwObLq6Dvueeem/x3o969exd+IgAAAChBeRX0b37zm9GrV69o1apVsecBAACAkpTXMehHHHFE/OMf/yj2LAAAAFCy8tqCniRJLF68OObPn/+x+/bYY4+CDwUAAAClJu/LrA0dOnST20mSRC6Xi7q6uoIPBQAAAKUm74L+s5/9LPbbb79izgIAAAAlK++C/uUvf3mTy60BAAAAhZPXSeJmzZoVPXv2jHfeeSciIt57771Yu3ZtUQcDAACAUpJXQW/UqFHsvvvuceWVV0ZExIMPPhhdu3aN5557rqjDAQAAQKnIq6Cfd955ccghh8T3v//9iIg44YQTol+/fjFs2LCiDgcAAAClIq+CvnDhwjjnnHPi85//fEREtG3bNkaMGBELFy4s5mwAAABQMvI6SdzBBx8cV1xxRTRp0iTKy8ujuro6rrrqKieNAwAAgALJawv6HXfcERs2bIj+/fvHvvvuG/3794/a2tqoqqoq9nwAAABQEvLagt6lS5eYPXt2LFq0KJYtWxaf//zno2vXrsWeDQAAAEpG3tdBnz59ekyZMiWqq6ujc+fOcfrpp8dRRx1VzNkAAACgZOS1i/vPfvazOOGEE+L555+PFi1axLPPPhsDBw6MW2+9tdjzAQAAQEnIq6CPGzcuxowZE/PmzYsHH3wwnn766RgzZkxce+21xZ4PAAAASkJeBX3lypXRq1evTZZ98YtfjA8++KAoQwEAAECpyesY9OOPPz6+/e1vx5IlS6J79+6xaNGiGDt2bBx33HHFng8AAABKQl4F/dZbb43Ro0dHRUVF1NTURJMmTWLIkCHxs5/9rNjzAQAAQEnIq6C3atUq7rnnnrjzzjvjX//6V3To0CF22CGvveMBAACAPOTVslevXh2XXnppXHfddRERccIJJ0SfPn1i9uzZRR0OAAAASkVeW9DPOuusmDlzZrRo0SJuv/322GWXXSIiYvTo0TFv3ryiDggAAAClIK+C/sgjj8SECRPiwAMPjC984Qvx61//Oj744IM49thjiz0fAAAAlIS8Cvq7774bHTt2jI4dO0ZERNOmTaOuri7Wr19f1OEAAACgVORV0CMiRo4cGS1btoyIiBEjRsSGDRuKNhQAAACUmrwK+vDhwyOXy0VExJ577lm/vHfv3sWZCgAAAEpMXgV9woQJRR6D7VVlZWWq66+oqEh1/QAAAPnKq6D36dPnE5fncrn429/+VtCBAAAAoBTlVdCXL18eCxcujG7dusXhhx9e5JEAAACg9ORV0OfPnx+33357XH311bFw4cK49tpr4+CDDy72bAAAAFAydsjnQWVlZXHeeefFa6+9FgMGDIhBgwbFSSedFC+++GKx5wMAAICSkNcW9PLy8vqzuEdE1NXVxe9+97uYPn26a6EDAABAAeRV0EeNGrVJQQcAAAAKK6+CftlllxV5DAAAAChteRX0HXbY4RO3oOdyuaitrS34UAAAAFBq8irov/jFL+oLenV1dVxxxRVxzTXXRNu2bYs6HAAAAJSKvAr6ueeeW//vd999N6688soYNGhQ9OzZs2iDAQAAQCnJ+zroERG1tbXx29/+NsrKyqJbt25FHQwAgG1PZWVlquuvqKhIdf0AWyOvgr7XXntFLpeLJEmiSZMmUVlZGa1atSr2bAAAAFAy8iros2bNioiIHXfcMfbYYw/HngMAAECB5VXQf//733/qfddcc03BhgEAAIBS9ZkF/b/+67/iuuuuixtuuCE2bNgQbdu2jZYtW9bfn8vlFHQAAAAogB0+684bbrghFi9eHP/4xz9i8ODBsX79+hgxYkQ8//zzsWDBgnj99dcbak4AAADYrn1mQU+SJD788MPYc889Y8qUKTFr1qz4+9//HrvsskvcfPPNUVNT01BzAgAAwHbtM3dx79evX+yxxx4xdOjQ+mXt2rWLnXbaKb73ve/FuHHjYuHChcWeEQAAALZ7n1nQZ86cGRER1dXVmyzv0aNH9OjRo3hTAQAAQInZrMusAZCfysrKVNdfUVGR6voBANh8n3kM+kZr166NioqK6NatWzRp0iS6d+8eP/nJT2L9+vXFng8AAABKQl5b0L/73e/GvffeG2eddVb06NEjXn/99Rg/fny88847ccsttxR7RgAA2CbYgwrYGnkV9F//+tdxyy23xBlnnFG/7IADDogLLrhAQQcAAIACyGsX9x122CHee++9TZa999570apVq6IMBQAAAKUmry3oo0ePjgsvvDAeeeSR6NGjRyxatCimTZsWl156abHnAwAAgJKQV0EfM2ZMdO7cOe6555544YUXokuXLnH77bfHmWeeWez5AAAAoCTkVdDvvvvuOPHEE+Pss88u9jwAAABQkvI6Bv2b3/xmzJ8/v9izAAAAQMnKawt6kiTx5JNPxvvvv/+x+wYMGFDwoQAAAKDU5FXQIyK+//3vR5IkmyzL5XJRV1dX8KEAAACg1ORd0KdMmRIHHHBAMWcBALYDlZWVqa6/oqIi1fUDwJbKu6B36tQpunXrVsxZAAAAoGTldZK4BQsWRJcuXeK1116LiIjq6upYunRpUQcDAACAUpJXQX/66adjr732iltuuSUiIv7whz/EbrvtFo888khRhwMAAIBSkdcu7j/4wQ9i+PDhcfXVV0dExNChQ2PevHkxatSo+Oc//1nUAQEAAKAU5LUFfeXKlXHcccdFs2bNIiKicePGMWDAgFi5cmVRhwMAAIBSkdcW9KOOOiq+973vxZtvvhnl5eVRXV0dlZWVroEOAAAABZJXQb/tttvi3HPPjXPPPTdqa2ujrKwsBg8eXH9MOgAAALB18iro77zzTvzqV7+Kurq6WLFiRXTo0CEaNWpU7NkAAACgZOR1DPpuu+0WPXv2jEsvvTSWLFminAMAAECB5VXQ77777vjyl78cd955Zxx00EHRuXPnGDVqVDz00EOxbt26Ys8IAAAA2728CvqwYcPi7rvvjmXLlsV9990XTZs2jTvuuCOOP/742HnnneOMM86IJUuWFHtWAAAA2G7ldQz6Qw89VP+1aNGiaN68eZx88slx4oknRtu2bWPMmDFxwgknxLx584o9LwAAAGyX8iroxx13XHTo0CGOP/74OOmkk6J///7RpEmT+vtzuVxUVFQUbUgAAADY3uVV0P/6179Gnz59IpfLfeL9AwcOjIEDBxZ0MAAAACgleRX0Qw45pNhzAAAAQEnL6yRxDeEvf/lL5HK5mDt3btqjAAAAQIPLREGvra2N888/P5o1a5b2KAAAAJCKvHZxHzp06Kfed9999231EOPGjYs+ffrE6tWrt/q5AAAAYFuUV0GfPHly9OrVK1q1ahV//etf48tf/nK0bNmyIAMsWbIkfvGLX8RTTz0VM2bMKMhzAgAAwLYmlyRJ8p8etMMOO8Rjjz0WBx54YDRp0iTmzp0b+++/f0EGOPXUU+Poo4+Os88+O7p37x4PPPBA9O7d+2OPq6qqiqqqqoj4qNRPnjy5IOsvtjfffDPV9Xfs2DHV9cufXv5Szh4hv/zyp0l++dMkv/xpkr90P/turoqKik88/1peW9BbtWoVy5Yti2XLlkVExIUXXhiXXnpp9OvXb6uG+v3vfx9vvPFGnHXWWf/xsSNHjoyRI0dGRETv3r3j8MMP36p1N5TKyspU1/+Nb3wj1fXLn17+Us4eIb/88qdJfvnTJL/8aZK/dD/7FkpeJ4k79thj46yzzopDDjkk9t5772jVqlUcddRR8ZWvfGWrVn7zzTfHM888E82aNYsdd9wxFi1aFIccckhMmDBhq54XAAAAtjV5bUG/44474sYbb4x33nknLrzwwujSpUs888wzcc0112zVyh966KFNbn/WLu4AAACwPcuroJeVlcVFF11Uf7umpib22WefuOeee4o2GAAAAJSSvAr6jjvuGLlc7mPLc7lc1NbWFmyYhQsXFuy5AAAAYFuSV0GPiPjRj34Uu+yyS5x99tlx6aWXRvfu3Ys4FgAAAJSWvAp6LpeLY445Jg466KA4++yzo0+fPnHUUUcVezYAAAAoGXmdxb1Lly7xwAMPxKRJkyIiYtCgQXHGGWfEyy+/XNThAAAAoFTktQX9kksuiVGjRkWSJHHeeedF37594+qrr4799tuvoMegAwAAQKnKq6CfddZZMWDAgHj33XejZ8+eERFxyimnfOwyaQAAAMCWyaug//jHP67/9/3337/Jfccee2xhJwIAAIASlFdB//dS/sYbb0SnTp2iSZMmkcvl4pprrinacAAAAFAq8iroCxYsiIiI2traaNKkSUybNi3233//og4GAAAApSSvs7hvlMvlNvkvAAAAUBh5bUEfOnRoREQkSRIRHx2T3rZt24iIuO+++4o0GgAAAJSOvAr6smXL6rea9+3bN9auXRvV1dVFHQwAAABKSV4F/dFHH/3YsrVr18Ybb7wR8+fPj5122im+8IUvFHo2AAAAKBl5FfQ//OEPH1v2wgsvREVFRUREHHLIIfGXv/ylsJMBAABACcmroA8cODByuVz9Megb5XK5+NOf/hStW7cuynAAAABQKvIq6BERU6ZMiQMOOKD+9pw5c+Ib3/hG9O3btyiDAQAAQCnJ+zJry5cvjyVLlsT69eujvLw8ysvLizkXAAAAlJS8t6Cff/75EfHRbu0tWrSIQw89tGhDAQAAQKnJq6C/9NJL9f9etWpV/OUvf4nrr78+Ij66Rvpee+0VY8aMKc6EAAAAUALyKuh77rnnJrcPPPDA6Nu3b1x00UVRXV0d7du3L8pwAAAAUCry3sX9iSeeiN/97nexdOnSuPzyy2PNmjUxderUaNmyZTHnAwAAgJKQ10nibrrppujTp0/8/ve/j3vuuSf+9a9/xY033hjf+ta3ij0fAAAAlIS8CvpPf/rTuOWWW+KJJ56ovxb6OeecE1OnTi3qcAAAAFAq8iroH374YZSVlUUul6tftmjRomjXrl3RBgMAAIBSktcx6KNHj47Ro0fHtGnTIpfLxcUXXxyzZs2Kyy67rMjjAQAAQGnIq6BfccUV0aVLl7jvvvti1113jbVr18b48ePjrLPOKvZ8AAAAUBLyPov7OeecE8OGDYsVK1ZEhw4dolmzZsWcCwAAAEpKXsegv/7669GvX79o0aJF7LLLLtGiRYvo379/vP7668WeDwAAAEpCXgX99NNPj4ULF0ZVVVXMmDEjbrvttli0aFEMGzas2PMBAABASchrF/eXXnopJk2aFMcff3z9so4dO8aZZ55ZtMEAAACglOS1BX3w4MHx5z//OdavXx81NTVRU1MTs2bNipNPPnmTZQAAAMCWyWsL+pQpU2LNmjUxbty4+mVJkkRExF133VW/rK6ursDjAQAAQGnIq6CPHz++2HMAAABASfuPBX3dunXRuXPnOOqoo+qX/fGPf4yvfvWr0bRp06IOBwAAAKXiM49Bnz9/fuy7774xcODATZYfc8wx0bNnz3jttdeKOhwAAACUis8s6BdeeGG0b98+5s2bt8nyOXPmRPv27eP73/9+UYcDAACAUvGZu7g//vjjcd9998WXvvSlTZb36tUrfvzjH7vMGgAAABTIZ25Bb9q0aVRXV3/ifW+//XZRBgIAAIBS9Jlb0E877bS46KKLora2Nr7yla9E69atY9WqVTF79uy4+OKLY/DgwQ01JwAAAGzXPrOgX3/99fHmm2/GueeeG7lcrn55kiRxwgknxE033VT0AQEAAKAUfGZBb9q0adx///1x/fXXx7x582L16tXRvHnz6NWrV+y6664NNSMAAABs9/7jddAjIrp27Rpdu3Yt9jL+mOkAABYCSURBVCwAAABQsj7zJHEAAABAw1DQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIAMUdAAAAMgABR0AAAAyQEEHAACADFDQAQAAIANSL+gTJ06M3XbbLdq0aRMDBgyIxYsXpz0SAAAANLhUC/pTTz0VF110Ufzud7+Lt956K7p16xYXXnhhmiMBAABAKlIt6AsWLIgLL7ww9t1332jcuHEMHTo0XnnllTRHAgAAgFTkkiRJ0h5ioyuvvDKqq6vjF7/4xcfuq6qqiqqqqoiIWLJkSUyePLmhx9sib775Zqrr79ixY6rrlz+9/KWcPUJ++eVPk/zyp0l++dMkf+l+9t1cFRUVMXfu3I8tL0thlk80b968qKqqijlz5nzi/SNHjoyRI0dGRETv3r3j8MMPb8DptlxlZWWq6//GN76R6vrlTy9/KWePkF9++dMkv/xpkl/+NMlfup99CyX1k8RFRCxevDgGDx4cEyZMiE6dOqU9DgAAADS41Av6qlWrYtCgQXHVVVdFv3790h4HAAAAUpFqQV+/fn2cfPLJccYZZ8SwYcPSHAUAAABSlWpBnz59ejzyyCNx+eWXR4sWLeq/Hn300TTHAgAAgAaX6kniTjrppMjQSeQBAAAgNakfgw4AAAAo6AAAAJAJCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABCjoAAABkgIIOAAAAGaCgAwAAQAYo6AAAAJABqRf0mTNnxj777BNt27aN448/Pt566620RwIAAIAGl2pBX7t2bQwZMiTGjx8fy5cvj5133jkuueSSNEcCAACAVKRa0J944ono2rVrHHnkkdG0adO44IIL4uGHH05zJAAAAEhFLkmSJK2VT548OSZOnFhfypcvXx7dunWLdevWfeyxVVVVUVVVFRERL7/8cuy1114NOmta3nrrrWjfvn3aY6RG/tLNX8rZI+SXX3755S9V8stfqvlLLfvChQvj7bff/tjyshRmqbd27dpo1KhR/e2ysrKoqan5xMeOHDkyRo4c2VCjZUbv3r1j7ty5aY+RGvlLN38pZ4+QX3755Ze/VMkvf6nmL+Xs/y7VXdybNm0atbW19bfr6uqirCzVvxkAAABAKlIt6OXl5bF48eL629XV1dGpU6cUJwIAAIB0NLrssssuS2vlHTt2jCuuuCL22Wef6NGjR1x66aWx2267xQknnJDWSJl0wAEHpD1CquQv3fylnD1CfvnlL2Xyy1/K5C/d/KWcfaNUTxIX8dF10C+44IJYvnx5HHbYYXHXXXdFu3bt0hwJAAAAGlzqBR0AAABI+Rh0AAAA4CMKOgAAAGSAgt7AJk6cGLvttlu0adMmBgwYUH8W+7Fjx0bXrl2jU6dO8b3vfS/q6uoiIuLDDz+MESNGRPv27WOXXXaJiRMnfuw5//Wvf0X79u2jsrKyQbNsiULmnzNnTpSVlUWLFi3qv55++ulUcuWr0K//k08+GUceeWS0bNky5s+f3+B5Nkehsj/66KObvOYtWrSIxo0bx7XXXptatnwU8rV/9dVX47DDDotWrVrFAQccEE899VQqmTZHofP36dMnWrVqFUcccUQsWrQolUybY3PzR0TMmzcvRo8eHaeffvomz/X0009H7969o02bNtG3b994/fXXGzTLlihk/nXr1sXkyZOjf//+8eCDDzZoji1VyPwPP/xw7LffftGqVavo06dPPP/88w2aZUsUMv/UqVNjr732ijZt2sTAgQNj6dKlDZplSxQy/0avvvpq7LjjjvHAAw80SIatUcj8U6ZMicaNG2/yGWDlypUNmmdzFfr1nzFjRhx00EHRokWLWLduXYPl2FKFyj9x4sSPff5r1KhR3H///Q2eqegSGszcuXOTDh06JP/4xz+Smpqa5Oyzz04GDx6czJ49O/nCF76QLFq0KHnrrbeSL37xi8n999+fJEmSXHfddckxxxyTrFmzJnn66aeTVq1aJYsXL97keUeOHJk0b948ueGGG9KIlbdC5//tb3+bnHDCCWlG2iyFzv/KK68k7du3TyZOnJisWbMmzWj/UbHe+0mSJHV1dckuu+ySzJ8/v6Fj5a3Q+Y888shkzJgxSW1tbXLbbbclu+22W5rx/qNC5z/ooIOSyy+/PKmpqUmuvPLK5Ktf/Wqa8f6jLcl/6aWXJnvuuWdyzDHHJIMGDdrk+fbee+9kwoQJSU1NTXLJJZckRx99dBqx8lbo/Lvuumty7LHHJj169EimTJmSRqTNUsj8S5YsSdq0aZP8+c9/Tmpra5PLL7882X///dOKlpdC52/btm0yZ86cpLa2Nvne976XnHbaaWlFy0uh3/8bDRgwIGnevHnmfwYKnf+mm25KLrjggjSibJFC5//zn/+cdOrUKZk6dWqydu3aNCJtlmK9/5MkSVatWpV06tQpeffddxsqToOxBb0BLViwIC688MLYd999o3HjxjF06NB45ZVXYsaMGXHqqadG165dY+edd44RI0bEww8/HBEf/ZXs3HPPjZ122il69eoVhx9+eMycObP+OZ988smYPXt2nHjiiWnFyluh8y9btiw6d+6cZqTNUuj8Y8eOje985zsxfPjw2GmnndKM9h8V472/0W9/+9vYfffdY/fdd2/oWHkrdP7nn38+TjvttGjUqFGcccYZ8c9//jM++OCDNCN+pkLmf+edd2LOnDlx0UUXRePGjeOHP/xhPPPMM7Fs2bKUU366Lcl//vnnx8svvxxf//rXN3muRYsWxZtvvhnDhw+Pxo0bx3e/+92YOXPmJlsesqaQ+SMiHn/88fjf//3f6Nq1a0NH2SKFzL9gwYIYPnx4HHbYYfU//6+88koasfJWyPxr166NysrK6N27dzRq1Ci+9rWvxXPPPZdGrLwV+v0f8dFW5FwuF717927IKFuk0PlL4bPfZ+W/4oororKyMo4//vho2rRpQ8fZbMV4/290xx13xNe+9rVo3bp1Q0RpUGVpD1BKTjnllE1uP/bYY3HYYYdFdXV19OjRo355eXl5zJgxIyIiqquro2PHjpvct3z58oiI2LBhQ4wePTp+9rOfxV133dUACbZOofMvW7YsZs6cGZ06dYqWLVvGFVdcEUOGDGmAJFum0PlnzZoVNTU10b1792jatGn9L+wsKnT2f3fTTTfFD3/4wyJNXhiFzn/EEUfE5MmT45JLLon7778/DjrooEz/kaaQ+f9vEW3cuHGUl5fHG2+8kdkPbVuSf+edd/7E56quro4OHTpELpeLiIi2bdtG48aNY8WKFVFeXl6kBFunkPkjItq3b1+cQYukkPkPPfTQOPTQQz/2XFlWyPy77rpr7LrrrhHx0WEwEydOjKOOOqpIkxdGod//77//fvzoRz+Khx9+OM4555ziDF1Ahc6/bNmymDp1alRWVkZ5eXmMGzcu+vXrV5zhC6CQ+Wtra+Oxxx6LHj16xEUXXRTt27eP2267LQ4++ODiBdhKhX79N6qrq4vx48fH1KlTCztwRtiCnpJ58+ZFVVVVjBkzJtauXRuNGjWqv6+srKz+mJLPuu/WW2+NvfbaK/r27duwwxdAIfIfc8wxce2118bSpUvj9ttvj3POOWebOBYzojD5lyxZEi1atIiXXnopbrnllhg2bFi89dZbDRtkCxQi+78/19KlS+OYY45pmOELoBD5x44dG+PGjYumTZvGueeeGz//+c8bNsRW2Nr8O++8c/Ts2TOuv/76WL9+fVRVVWX+/Av/Lt/8n+b/fk++35cVW5t/W1fI/G+88UZcfPHFcf311xdj1KIoVP4zzzwzWrZsGX/84x/jxz/+cbHGLbhC5L/88svjtNNOy/ReY5+mEPmHDBkSN910Uyxfvjz+67/+K77+9a/HqlWrijl2wWxt/rfeeivWrVsX3bt3r98yfeqpp0ZNTU2xRy+IQv7+++1vfxvdunWL/fbbrxijpk5BT8HixYtj8ODBMWHChOjUqVM0bdo0amtr6++vq6uLxo0bR0R86n0rVqyIsWPHxg033NDg82+tQuSPiOjTp0+ceuqp0ahRozjyyCPjiCOOiD//+c8NG2YLFCr/hg0bYsyYMdGsWbPo379/7LfffvH44483bJjNVKjsG40bNy5Gjx4dO+ywbfwqK0T+JEnipJNOimuvvTbWrVsXM2bMiJNPPjnefffdBs+zuQr1+k+aNCmmTZsW3bt3j9dffz1atmwZHTp0aNgwW2Bz8n+a//s9+X5fFhQi/7askPlXrVoVgwYNiquuuip69uxZrJELqpD5J06cGGvWrIlhw4Z96knUsqYQ+V944YX4zW9+s039UWKjQr3+xx57bBx99NHRqFGjGDp0aHTu3DnmzZtXzNELohD5N2zYEE2bNo2LL744mjRpEiNGjIgNGzbEyy+/XOzxt1qhf//fdNNNcf755xdj1EzYNj7Vbkf+/X+qG3fJKS8vrz+jYcRHuzB26tTpM++766676ncP2XHHHWPSpEnxox/9KP7f//t/DRtoMxUqf0TEjTfeuMlxpxt3+cyyQubv2rVrvPHGG5s8///dspYlhcy+8fb06dMz/57fqFD533rrrXjuuefiW9/6VpSVlUW/fv2iY8eOMXv27IYNtJkK+fr37Nkz5s6dG0uXLo0RI0ZE8+bNN9lVLos2N/+nKS8vj+rq6vpd/d99991Yv3595nf7LlT+bVUh869fvz4GDx4cQ4YMieHDhxdt5kIqVP7XXnstpk+fHhEf/bFq1KhR8fe//714gxdIofKPHz8+3njjjWjXrl3suOOO8Ze//CWGDh0al19+eVHn31qFfP+PGTMmPvzww/rb2+Nnv0/TqVOn2LBhQ6xYsWKT5Vn+7BdR+N//Tz31VCxatGibOP/WFkv7LHWlpKamJunXr18yduzYTZbPnj076dChQ/Lqq68mK1euTHr16pVMmjQpSZKPzmTct2/fZPXq1clzzz2XtG7dOlmwYMHHnvvMM8/M/FncC53/7LPPTkaPHp3U1NQkc+bMSVq2bJm8+uqrDR0rb4XO/+Mf/zg57rjjkjVr1iSzZs1K2rZtm7z99tsNHSsvxXjvX3zxxck555zTkDG2WCHzb9iwIencuXMyceLEZMOGDcmTTz6ZtG7dOlm4cGEa0fJSjNe/rq4ueeaZZ5LevXsnlZWVDRlns21J/o3uuuuuTzyL+/jx45P169cnl112WdKvX7+iZ9gahc6/Ud++fTN/BuskKXz+4cOHJ6NHjy763IVSyPwvvvhi0q5du+T5559P6urqkquvvjrzV3Eo1vs/SbaNn4FC5+/fv39y7bXXJnV1dcn06dOTtm3bZvos3oXOP3To0GTUqFHJunXrkkmTJiXdunVLampqip5jSxXj/X/66acnV199dVHnTpuC3oAefPDBJCKS5s2bb/I1a9asZOzYscnnP//5pGPHjklFRUVSV1eXJEmSfPDBB8mZZ56ZfO5zn0t22WWX5J577vnE594WCnqh869cuTI5+eSTkzZt2iQ9evRI7r333rSi5aXQ+T/88MPkrLPOSj73uc8le+65ZzJjxoy0ov1Hxci+8847J88++2xakTZLofM/8cQTyYEHHpi0bNky2X333ZNf/epXaUXLSzF+9/Xo0SPZc889k5tvvjmNSJtlS/Jv9EkfUObNm5fsv//+SatWrZK+fftm+o8zSVL4/BttC+UkSQqbf968eUlEJDvttNMmzzVhwoSGjpW3Qr/+EydOTHbZZZekdevWSb9+/ZJ//vOfDRlnsxXr/Z8k28bPQKHzL1y4MOnfv3/SqlWrZJ999klmzpzZkHE2W6Hzr1y5MjnppJOSNm3aJPvvv38yZ86choyz2Qqdf9myZUnLli2TFStWNGSMBpdLkiRJYcM9AAAA8G8cgw4AAAAZoKADAABABijoAAAAkAEKOgAAAGSAgg4AAAAZoKADAABABijoAAAAkAEKOgCUiIULF0Yul/vY1+zZs9MeDQCIiLK0BwAAGlZlZWUcdNBB9bf33XffFKcBADayBR0ASsy+++4bhx56aP1XixYt4oorroiOHTtG+/bt49xzz40PPvig/vGnnXbaJlvcDz744BSnB4Dtl4IOACXul7/8ZVx55ZXxk5/8JCorK+Pee++Nn/zkJ5s8plevXvHXv/41jjnmmJSmBIDtn13cAaDETZo0KY477rj49re/HRERTz/9dEyZMiVuvPHG+se0a9cuDj300OjQoUP861//SmtUANiu2YIOACVu+fLl0aNHj/rbPXr0iOrq6vrbq1atio4dO6YxGgCUFAUdAEpcly5dYtGiRfW3FyxYEJ07d46IiLVr18acOXOcSA4AGoCCDgAlbtiwYTFt2rS45ZZbYtKkSXHXXXfF6aefHqtWrYof/OAHsXLlyth9993jscceixUrVsR7770Xr7zyStpjA8B2xzHoAFDizjzzzFi6dGlcd911sXr16hgyZEhcdtll8fjjj8f48eMjIuIb3/jGJt9z6aWXxuTJk9MYFwC2W7kkSZK0hwAAsufRRx+NI444Il566aXYa6+96pcffvjh0alTJwUdAArMFnQA4BO1bt06DjnkkNhpp502Wd6zZ8/43Oc+l9JUALD9sgUdAAAAMsBJ4gAAACADFHQAAADIAAUdAAAAMkBBBwAAgAxQ0AEAACADFHQAAADIgP8PGCWrEchz93YAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 1008x504 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.figure(figsize = (14,7), facecolor = 'w')\n",
    "\n",
    "plt.bar([i for i in range(2004, 2018)], sustain, width=.5, color = colors['grey'])\n",
    "plt.xticks([i for i in range(2004, 2018)], [i for i in range(2004, 2018)], fontproperties = regluar_font)\n",
    "plt.yticks(fontproperties = regluar_font)\n",
    "plt.grid(axis = 'y')\n",
    "plt.ylim(0,10)\n",
    "plt.ylabel('Средняя устойчивость региона',  fontproperties = medium_font)\n",
    "plt.xlabel('Год', fontproperties = medium_font)\n",
    "plt.tight_layout()\n",
    "plt.savefig('analysis/percolation_regions/plots_v4/Mean Sustainability.png')\n",
    "# plt.yticks([i for i in range(len(sustain))], [i for i in range(2004, 2018)])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_list = {year : gpd.read_file(f'analysis/percolation_regions/{year} region cores sustain_v2.gpkg') for year in range(2004,2018)}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017 region cores sustain_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None]"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "[\n",
    "    df_list[year].dropna(\n",
    "        subset = ['parent']\n",
    "    ).dissolve(by = 'parent').reset_index().to_file(\n",
    "        f'analysis/percolation_regions/{year} region cores sustain_v2.gpkg'\n",
    "    ) for year in range(2004,2018)\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None]"
      ]
     },
     "execution_count": 38,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "[\n",
    "    bounds.drop(\n",
    "        columns = ['parent', 'sustain']\n",
    "    ).merge(\n",
    "        i, on = 'NAME', how = 'right'\n",
    "    ).dropna(subset = ['geometry']).dissolve(by = ['parent','percolation_threshold']).reset_index().to_file(\n",
    "        f'analysis/percolation_regions/evo/{i.year.unique()[0]}_evolution_v2.gpkg',\n",
    "        driver = 'GPKG'\n",
    "    ) for i in percolation_regions\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2004_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2005_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2006_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2007_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2008_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2009_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2010_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2011_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2012_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2013_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2014_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2015_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2016_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "ename": "CPLE_AppDefinedError",
     "evalue": "b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mfiona/_err.pyx\u001b[0m in \u001b[0;36mfiona._err.GDALErrCtxManager.__exit__\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mCPLE_AppDefinedError\u001b[0m: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'fiona._shim.gdal_flush_cache'\n",
      "Traceback (most recent call last):\n",
      "  File \"fiona/_err.pyx\", line 201, in fiona._err.GDALErrCtxManager.__exit__\n",
      "fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE \"rtree_2017_evolution_v2_geom\" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None,\n",
       " None]"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "[\n",
    "    bounds.drop(\n",
    "        columns = ['parent', 'sustain']\n",
    "    ).merge(\n",
    "        i, on = 'NAME', how = 'right'\n",
    "    ).dropna(subset = ['geometry']).dissolve(by = ['parent','percolation_threshold']).reset_index().to_file(\n",
    "        f'analysis/percolation_regions/evo/{i.year.unique()[0]}_evolution_v2.gpkg',\n",
    "        driver = 'GPKG'\n",
    "    ) for i in percolation_regions\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mtopn\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.\n",
      "  \"\"\"Entry point for launching an IPython kernel.\n"
     ]
    }
   ],
   "source": [
    "pd.Series([f'percolation_{eps}' for eps in epses]).rename('percolation_threshold').to_csv('analysis/percolation_regions/evo/Atlas.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
